# Generated by Django 5.2.1 on 2025-05-19 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('nik', models.CharField(max_length=32)),
                ('npwp', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('staff', 'Staff'), ('contract', 'Contract'), ('outsourced', 'Outsourced')], max_length=16)),
                ('pay_period', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Biweekly'), ('weekly', 'Weekly')], max_length=16)),
                ('work_type', models.CharField(choices=[('9-5', '9-5'), ('shift', 'Shift')], max_length=16)),
                ('bank_name', models.CharField(max_length=64)),
                ('bank_account_number', models.CharField(max_length=64)),
                ('account_holder_name', models.CharField(max_length=128)),
                ('base_salary', models.IntegerField()),
                ('ptkp_status', models.CharField(choices=[('TK0', 'TK0'), ('K0', 'K0'), ('K1', 'K1'), ('K2', 'K2'), ('K3', 'K3')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('hours_worked', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_salary', models.IntegerField()),
                ('tax_deduction', models.IntegerField()),
                ('other_deductions', models.IntegerField()),
                ('net_salary', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.payrollrun')),
            ],
        ),
    ]
