# Generated by Django 5.2.1 on 2025-05-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_benefittype_employeebenefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebenefit',
            name='benefit_type',
            field=models.CharField(choices=[('health_insurance', 'Health Insurance'), ('bpjs_kesehatan', 'BPJS Kesehatan'), ('bpjs_ketenagakerjaan', 'BPJS Ketenagakerjaan'), ('meal', 'Meal Allowance'), ('transport', 'Transport Allowance'), ('communication', 'Communication Allowance'), ('overtime', 'Overtime Allowance'), ('position', 'Position Allowance'), ('attendance', 'Attendance Allowance'), ('thr', 'Holiday Allowance (THR)'), ('bonus', 'Bonus'), ('pension', 'Pension Fund'), ('housing', 'Housing Allowance'), ('child', 'Child Allowance'), ('other', 'Other')], max_length=32),
        ),
        migrations.DeleteModel(
            name='BenefitType',
        ),
    ]
