# Generated by Django 5.2.1 on 2025-05-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_employeebenefit_benefit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollitem',
            name='bpjs_kesehatan_employee',
            field=models.IntegerField(default=0, help_text='BPJS Kesehatan portion paid by employee'),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='bpjs_kesehatan_employer',
            field=models.IntegerField(default=0, help_text='BPJS Kesehatan portion paid by employer'),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='bpjs_ketenagakerjaan_employee',
            field=models.IntegerField(default=0, help_text='BPJS Ketenagakerjaan portion paid by employee'),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='bpjs_ketenagakerjaan_employer',
            field=models.IntegerField(default=0, help_text='BPJS Ketenagakerjaan portion paid by employer'),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='total_deductions',
            field=models.IntegerField(default=0, help_text='Sum of all deductions (tax + BPJS + other)'),
        ),
    ]
