# Generated by Django 5.2.1 on 2025-05-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payrollitem_bpjs_kesehatan_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollitem',
            name='bpjs_jp_employee',
            field=models.IntegerField(default=0, help_text='BPJS Ketenagakerjaan JP portion paid by employee'),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='bpjs_jp_employer',
            field=models.IntegerField(default=0, help_text='BPJS Ketenagakerjaan JP portion paid by employer'),
        ),
        migrations.AlterField(
            model_name='employeebenefit',
            name='benefit_type',
            field=models.CharField(choices=[('meal', 'Meal Allowance'), ('transport', 'Transport Allowance'), ('communication', 'Communication Allowance'), ('overtime', 'Overtime Allowance'), ('position', 'Position Allowance'), ('attendance', 'Attendance Allowance'), ('thr', 'Holiday Allowance (THR)'), ('bonus', 'Bonus'), ('pension', 'Pension Fund'), ('housing', 'Housing Allowance'), ('child', 'Child Allowance'), ('other', 'Other')], max_length=32),
        ),
        migrations.CreateModel(
            name='EmployeeDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('loan', 'Loan Repayment'), ('union', 'Union Fee'), ('other', 'Other')], max_length=32)),
                ('amount', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
    ]
