from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('employees/', views.employee_list, name='employee_list'),
    path('employees/add/', views.employee_add, name='employee_add'),
    path('employees/<int:pk>/edit/', views.employee_edit, name='employee_edit'),
    path('employees/<int:pk>/delete/', views.employee_delete, name='employee_delete'),
    path('work-calendar/', views.work_calendar, name='work_calendar'),
    path('attendance/', views.attendance_list, name='attendance_list'),
    path('attendance/add/', views.attendance_add, name='attendance_add'),
    path('attendance/<int:pk>/edit/', views.attendance_edit, name='attendance_edit'),
    path('attendance/<int:pk>/delete/', views.attendance_delete, name='attendance_delete'),
    path('leave/', views.leave_list, name='leave_list'),
    path('leave/add/', views.leave_add, name='leave_add'),
    path('leave/<int:pk>/edit/', views.leave_edit, name='leave_edit'),
    path('leave/<int:pk>/delete/', views.leave_delete, name='leave_delete'),
    path('benefits/', views.employee_benefit_list, name='employee_benefit_list'),
    path('benefits/add/', views.employee_benefit_add, name='employee_benefit_add'),
    path('benefits/<int:pk>/edit/', views.employee_benefit_edit, name='employee_benefit_edit'),
    path('benefits/<int:pk>/delete/', views.employee_benefit_delete, name='employee_benefit_delete'),
    path('payroll/', views.payroll_run_list, name='payroll_run_list'),
    path('payroll/add/', views.payroll_run_add, name='payroll_run_add'),
    path('payroll/<int:pk>/edit/', views.payroll_run_edit, name='payroll_run_edit'),
    path('payroll/<int:pk>/delete/', views.payroll_run_delete, name='payroll_run_delete'),
    path('payroll/<int:pk>/detail/', views.payroll_run_detail, name='payroll_run_detail'),
    path('payroll/<int:run_id>/generate-items/', views.generate_payroll_items, name='generate_payroll_items'),
    path('payroll/<int:run_id>/export-payslips/', views.export_payslips_zip, name='export_payslips_zip'),
    path('payroll/<int:run_id>/export-csv/', views.export_payroll_csv, name='export_payroll_csv'),
    path('compensation/<int:pk>/payslip/', views.payslip_view, name='payslip_view'),
    path('compensation/', views.compensation_list, name='compensation_list'),
    path('compensation/add/', views.compensation_add, name='compensation_add'),
    path('compensation/<int:pk>/edit/', views.compensation_edit, name='compensation_edit'),
    path('compensation/<int:pk>/delete/', views.compensation_delete, name='compensation_delete'),
    path('reports/tax-bpjs/', views.tax_bpjs_report, name='tax_bpjs_report'),
] 